Name: "kubviz-client"
ChartName: "kubviz/client"
RepoName: "kubviz"
RepoURL: "https://kube-tarian.github.io/kubviz/"
Namespace: "observability"
ReleaseName: "kubviz-client"
Version: "0.1.9"
CreateNamespace: true