Name: "signoz"
ChartName: "signoz/signoz"
RepoName: "signoz"
RepoURL: "https://charts.signoz.io"
Namespace: "observability"
ReleaseName: "signoz"
Version: "0.14.0"
CreateNamespace: true
Override:
  Values:
    "clickhouse.password": admin
    "frontend.ingress.enabled": true
    # "frontend.ingress.annotations.cert-manager.io/cluster-issuer": letsencrypt-prod-cluster
    # "frontend.ingress.annotations.nginx.ingress.kubernetes.io/backend-protocol": HTTPS
    # "frontend.ingress.annotations.nginx.ingress.kubernetes.io/force-ssl-redirect": true
    # "frontend.ingress.annotations.nginx.ingress.kubernetes.io/ssl-redirect": true
    "frontend.ingress.hosts[0].host": "signoz.capten.intelops.app"
    "frontend.ingress.hosts[0].paths[0].path": "/"
    "frontend.ingress.hosts[0].paths[0].pathType": frontend.ingress.hosts[0].paths[0].pathType|ImplementationSpecific
    "frontend.ingress.hosts[0].paths[0].port": 3301
    "frontend.ingress.tls[0].hosts[0]": signoz.capten.intelops.app
    "frontend.ingress.tls[0].secretName": frontend.ingress.tls[0].secretName|cert-sig