ports:
  traefik:
    expose: false
    port: 9000
  web:
    expose: true
    port: 8000
    nodePort: 32080
  websecure:
    expose: true
    port: 8443
    nodePort: 32443
service:
  enabled: "true"
  type: NodePort