AwsAccessKey: "accesskey"
AwsSecretKey: "secretkey"
AlbName: "talosalb-9"
PrivateSubnet: "192.0.1.0/24"
Region: "us-west-2"
SecurityGroupName: "talossg-9"
VpcCidr: "192.0.0.0/16"
VpcName: "talosvpc-9"
InstanceType: "m6i.xlarge"
NodeMonitoringEnabled: "false"
MasterCount: "1"
WorkerCount: "5"
TraefikHttpPort: "32080"
TraefikHttpsPort: "32443"
TalosTg: "talos-tg-9"
TraefikTg80Name: "talos-tg-80-9"
TraefikTg443Name: "talos-tg-443-9"
TraefikLbName: "traefik-lb-9"
TerraformBackendConfigs:
  - "bucket=capten-talos-state"
  - "dynamodb_table=intelops-tf-state"