AwsAccessKey: ""
AwsSecretKey: ""
AlbName: "talosalb"
PrivateSubnet: "10.0.1.0/24"
Region: "us-west-1"
SecurityGroupName: "talossg"
VpcCidr: "10.0.0.0/16"
VpcName: "talosvpc"
InstanceType: "t2.medium"
NodeMonitoringEnabled: "false"
MasterCount: "3"
WorkerCount: "3"
#GlobalValues:
#  ingress.hostname: "test.optimizer.com"
PostInstall:
#  - Name: "openebs-jiva"
#    ChartName: "tools/openebs-jiva"
#    RepoName: "tools"
#    RepoURL: "https://kube-tarian.github.io/helmrepo-supporting-tools"
#    Namespace: "openebs-jiva"
#    ReleaseName: "openebs-jiva"
#    Version: "1.0.3"
#    CreateNamespace: true
#    MakeNsPrivilege: true
#  - Name: "traefik"
#    ChartName: "traefik/traefik"
#    RepoName: "traefik"
#    RepoURL: "https://traefik.github.io/charts"
#    Namespace: "traefik"
#    ReleaseName: "traefik"
#    Version: "20.8.0"
#    CreateNamespace: true
#  - Name: "temporal"
#    ChartName: "tools/temporal"
#    RepoName: "tools"
#    RepoURL: "https://kube-tarian.github.io/helmrepo-supporting-tools"
#    Namespace: "default"
#    ReleaseName: "temporal"
#    Version: "0.1.1"
#    CreateNamespace: true
  - Name: "loki"
    ChartName: "grafana/loki-stack"
    RepoName: "grafana"
    RepoURL: "https://grafana.github.io/helm-charts"
    Namespace: "observability"
    ReleaseName: "loki"
    CreateNamespace: true
    Override:
      "grafana.enabled": true
      "grafana.ingress.enabled": true
      "grafana.ingress.hosts": '{"grafana.dev.optimizor.app"}'
      "prometheus.enabled": true
      "grafana.sidecar.datasources.enabled": true
      "grafana.sidecar.dashboards.enabled": true
#  - Name: "cert-manager"
#    ChartName: "jetstack/cert-manager"
#    RepoName: "jetstack"
#    RepoURL: "https://charts.jetstack.io"
#    Namespace: "cert-manager"
#    ReleaseName: "cert-manager"
#    Version: "v1.11.0"
#    CreateNamespace: true
#    Override:
#      "installCRDs": true
  - Name: "kad"
    ChartName: "kad/kad"
    RepoName: "kad"
    RepoURL: "https://kube-tarian.github.io/kad"
    Namespace: "default"
    ReleaseName: "kad"
    Version: "0.1.12"
    CreateNamespace: true
    SecretInfos:
      - FilePath: "./intermediate/cert-chain.pem"
        Key: "ingressroute.mtls.caCrt"
      - FilePath: "./server/server.crt"
        Key: "ingressroute.mtls.tlsCrt"
      - FilePath: "./server/server.key"
        Key: "ingressroute.mtls.tlsKey"
#  - Name: "signoz"
#    ChartName: "signoz/signoz"
#    RepoName: "signoz"
#    RepoURL: "https://charts.signoz.io"
#    Namespace: "observability"
#    ReleaseName: "signoz"
#    CreateNamespace: true

