AwsAccessKey: ""
AwsSecretKey: ""
AlbName: "talosalb"
PrivateSubnet: "10.0.1.0/24"
Region: "us-west-1"
SecurityGroupName: "talossg"
VpcCidr: "10.0.0.0/16"
VpcName: "talosvpc"
InstanceType: "t2.medium"
NodeMonitoringEnabled: "false"
MasterCount: "3"
WorkerCount: "3"
TraefikHttpPort: "32080"
TraefikHttpsPort: "32443"
#GlobalValues:
#  ingress.hostname: "test.optimizer.com"
PostInstall:
  - Name: "openebs-jiva"
    ChartName: "tools/openebs-jiva"
    RepoName: "tools"
    RepoURL: "https://kube-tarian.github.io/helmrepo-supporting-tools"
    Namespace: "openebs-jiva"
    ReleaseName: "openebs-jiva"
    Version: "1.0.5"
    CreateNamespace: true
    MakeNsPrivilege: true
  - Name: "traefik"
    ChartName: "traefik/traefik"
    RepoName: "traefik"
    RepoURL: "https://traefik.github.io/charts"
    Namespace: "traefik"
    ReleaseName: "traefik"
    Version: "20.8.0"
    CreateNamespace: true
    Override:
      "service.type": NodePort
      note: need to provide the case-sensitive key as part of value
      "ports.websecure.nodePort": ports.websecure.nodePort|32443
      "ports.web.nodePort": ports.web.nodePort|32080
  - Name: "temporal"
    ChartName: "tools/temporal"
    RepoName: "tools"
    RepoURL: "https://kube-tarian.github.io/helmrepo-supporting-tools"
    Namespace: "capten"
    ReleaseName: "temporal"
    Version: "0.1.2"
    CreateNamespace: true
    Override:
      "server.config.persistence.default.cassandra.port": 9042
      "server.config.persistence.visibility.cassandra.port": 9042
  - Name: "loki"
    ChartName: "grafana/loki-stack"
    RepoName: "grafana"
    RepoURL: "https://grafana.github.io/helm-charts"
    Namespace: "observability"
    ReleaseName: "loki"
    CreateNamespace: true
    Override:
      "grafana.enabled": true
      "grafana.ingress.enabled": true
      "grafana.ingress.hosts": '{"grafana.dev.optimizor.app"}'
      "prometheus.enabled": true
      "grafana.sidecar.datasources.enabled": true
      "grafana.sidecar.dashboards.enabled": true
  - Name: "cert-manager"
    ChartName: "jetstack/cert-manager"
    RepoName: "jetstack"
    RepoURL: "https://charts.jetstack.io"
    Namespace: "cert-manager"
    ReleaseName: "cert-manager"
    Version: "v1.11.0"
    CreateNamespace: true
    Override:
      "installCRDs": installCRDs|true
  - Name: "kad"
    ChartName: "kad/kad"
    RepoName: "kad"
    RepoURL: "https://kube-tarian.github.io/kad"
    Namespace: "default"
    ReleaseName: "kad"
    Version: "0.1.16"
    CreateNamespace: true
    Override:
      "ingressroute.mtls.enabled": true
    SecretInfos:
      - FilePath: "./intermediate/cert-chain.pem"
        Key: "ingressroute.mtls.caCrt"
      - FilePath: "./server/server.crt"
        Key: "ingressroute.mtls.tlsCrt"
      - FilePath: "./server/server.key"
        Key: "ingressroute.mtls.tlsKey"
  - Name: "signoz"
    ChartName: "signoz/signoz"
    RepoName: "signoz"
    RepoURL: "https://charts.signoz.io"
    Namespace: "observability"
    ReleaseName: "signoz"
    CreateNamespace: true
    Override:
      "clickhouse.password": admin
  # - Name: "quality-trace"
  #   ChartName: "quality-trace/quality-trace"
  #   RepoName: "quality-trace"
  #   RepoURL: "https://kube-tarian.github.io/quality-trace"
  #   Namespace: "quality-trace"
  #   ReleaseName: "quality-trace"
  #   CreateNamespace: true
  #   Override:
  #     "clickhouse.url": http://signoz-clickhouse.observability.svc.cluster.local:9000
  - Name: "kyverno"
    ChartName: "kyverno/kyverno"
    RepoName: "kyverno"
    RepoURL: "https://kyverno.github.io/kyverno/"
    Namespace: "kyverno"
    ReleaseName: "kyverno"
    CreateNamespace: true
    Override:
      "target.loki.host": http://loki.observability.svc.cluster.local:3100
      "target.loki.path": /loki/api/v1/push
      "target.loki.minimumPriority": warning
      "target.loki.skipExistingOnStartup": true
      "target.loki.sources[0]": kyverno
  - Name: "velero"
    ChartName: "vmware-tanzu/velero"
    RepoName: "vmware-tanzu"
    RepoURL: "https://vmware-tanzu.github.io/helm-charts"
    Namespace: "velero"
    ReleaseName: "velero"
    CreateNamespace: true
  - Name: "kubescape"
    ChartName: "kubescape/kubescape-prometheus-integrator"
    RepoName: "kubescape"
    RepoURL: "https://kubescape.github.io/helm-charts/"
    Namespace: "kubescape-prometheus"
    ReleaseName: "kubescape-prometheus"
    CreateNamespace: true
    Override:
      "kubescape.prometheusAnnotation.enabled": kubescape.prometheusAnnotation.enabled|true
      "kubescape.serviceMonitor.enabled": kubescape.serviceMonitor.enabled|false
  - Name: "falco"
    ChartName: "falcosecurity/falco"
    RepoName: "falcosecurity"
    RepoURL: "https://falcosecurity.github.io/charts"
    Namespace: "falco"
    ReleaseName: "falco"
    CreateNamespace: true
    Override:
      "driver.kind": ebpf
  - Name: "crossplane"
    ChartName: "crossplane-stable/crossplane"
    RepoName: "crossplane-stable"
    RepoURL: "https://charts.crossplane.io/stable"
    Namespace: "crossplane-system"
    ReleaseName: "crossplane"
    CreateNamespace: true
    Override:
     "provider.packages[0]": xpkg.upbound.io/crossplane-contrib/provider-aws:v0.33.0
      "provider.packages[1]": xpkg.upbound.io/crossplane-contrib/provider-gcp:v0.22.0
      "provider.packages[2]": xpkg.upbound.io/crossplane-contrib/provider-azure:v0.20.1
      "provider.packages[3]": xpkg.upbound.io/digitalocean/provider-digitalocean:v0.2.0
      "provider.packages[4]": xpkg.upbound.io/civo/provider-civo:v0.1
  - Name: "kubviz-client"
    ChartName: "kubviz/client"
    RepoName: "kubviz"
    RepoURL: "https://kube-tarian.github.io/kubviz/"
    Namespace: "observability"
    ReleaseName: "kubviz-client"
    CreateNamespace: true
  - Name: "kubviz-agent"
    ChartName: "kubviz/agent"
    RepoName: "kubviz"
    RepoURL: "https://kube-tarian.github.io/kubviz/"
    Namespace: "observability"
    ReleaseName: "kubviz-agent"
    CreateNamespace: true
    Override:
      "nats.host": kubviz-client-nats.observability.svc.cluster.local
  - Name: "vault-operator"
    ChartName: "banzaicloud-stable/vault-operator"
    RepoName: "banzaicloud-stable"
    RepoURL: "https://kubernetes-charts.banzaicloud.com"
    Namespace: "vault-infra"
    ReleaseName: "vault-operator"
    CreateNamespace: true
  - Name: vault-post
    ChartName: "tools/vault-post"
    RepoName: "tools"
    RepoURL: "https://kube-tarian.github.io/helmrepo-supporting-tools"
    Namespace: "deafault"
    ReleaseName: "vault-post"
    CreateNamespace: true  
  - Name: vault-secrets-webhook
    ChartName: banzaicloud-stable/vault-secrets-webhook
    RepoName: banzaicloud-stable
    RepoURL: https://kubernetes-charts.banzaicloud.com
    Namespace: vault-infra
    ReleaseName: vault-secrets-webhook
    CreateNamespace: true  
