AwsAccessKey: "accesskey"
AwsSecretKey: "secretkey"
AlbName: "talosalb-3"
PrivateSubnet: "10.0.1.0/24"
Region: "us-west-2"
SecurityGroupName: "talossg-3"
VpcCidr: "10.0.0.0/16"
VpcName: "talosvpc-3"
InstanceType: "m6i.xlarge"
NodeMonitoringEnabled: "false"
MasterCount: "3"
WorkerCount: "3"
TraefikHttpPort: "32080"
TraefikHttpsPort: "32443"
TalosTg: "talos-tg-3"
TraefikTg80Name: "talos-tg-80-3"
TraefikTg443Name: "talos-tg-443-3"
TraefikLbName: "traefik-lb-3"
TerraformBackendConfigs:
  - "bucket=intelops-tf-state-3"
  - "dynamodb_table=intelops-tf-state"